var replaceCommand = [/smiling|happy/i, /joy/i, /nice/i, /smile/i, /sweat/i, /laugh/i, /wink/i, /smiling eyes/i, /delicious/i, /relieved/i, /in love/i, /smirking /i, /unamused/i, /cold sweat/i, /pensive/i, /confounded/i, /kissing/i, /kissing/i, /tongue/i, /stuck-out tongue/i, /disappointed/i, /angry/i, /pissed off/i, /crying/i, /persevering/i, /triumphing/i, /relieved/i, /fearful/i, /weary/i, /sleepy/i, /whimsical/i, /crying a river/i, /worried/i, /screaming/i, /astonished/i, /flushed/i, /dizzy/i, /medical/i, /grinning cat/i, /cat tears/i, /smiling cat/i, /smiling cat face with heart-shaped eyes/i, /cat face with wry smile/i, /cat face with closed eyes/i, /pouting cat face/i, /crying cat/i, /weary cat/i, /no good/i, /ok/i, /bowing/i, /see-no-evil/i, /hear-no-evil/i, /speak-no-evil/i, /raising one hand/i, /raising both hands/i, /frowning/i, /pouting face/, /folded hands/i, /rocket/i, /railway/i, /high-speed train/i, /high speed train/i, /metro/i, /station/i, /bus/i, /bus stop/i, /ambulance/i, /fire engine/i, /police car/i, /taxi/i, /automobile/i, /recreational vehicle/i, /delivery truck/i, /ship/i, /speedboat/i, /traffic light/i, /construction/i, /revolving light/i, /flag/i, /door/i, /no entry/i, /smoking symbol/i, /no smoking/i, /bicycle/i, /pedestrian/i, /mens/i, /womens/i, /restroom/i, /baby/i, /toilet/i, /water|wc/i, /bath/i, /cool/i, /free/i, /ID/i, /new/i, /NG/i, /ok/i];
var replaceOutput = ['😁', '😂', '😃', '😄', '😅', '😆', '😉', '😊', '😋', '😌', '😍', '😏', '😒', '😓', '😔', '😖', '😘', '😚', '😜', '😝', '😞', '😠', '😡', '😢', '😣', '😤', '😥', '😨', '😩', '😪', '😫', '😭', '😰', '😱', '😲', '😳', '😵', '😷', '😸', '😹', '😺', '😻', '😼', '😽', '😾', '😿', '🙀', '🙅', '🙆', '🙇', '🙈', '🙉', '🙊', '🙋', '🙌', '🙍', '🙎', '🙏', '🚀', '🚃', '🚄', '🚅', '🚇', '🚉', '🚌', '🚏', '🚑', '🚒', '🚓', '🚕', '🚗', '🚙', '🚚', '🚢', '🚤', '🚥', '🚧', '🚨', '🚩', '🚪', '🚫', '🚬', '🚭', '🚲', '🚶', '🚹', '🚺', '🚻', '🚼', '🚽', '🚾', '🛀', '🆒', '🆓', '🆔', '🆕', '🆖', '🆗', '🆘'];

document.getElementById('text').addEventListener('input', function() {
  var text = document.getElementById('text').value;
  for (var i = 0; i < replaceCommand.length; i++) {
    text = text.replace(replaceCommand[i], replaceOutput[i]);
  }
  document.getElementById('text').value = text;
});
